### ISSUE TITLE
Bad indentation in get_df docs dtype example

### ISSUE THREAD

**Issue by DrGFreeman** [DrGFreeman/dynamo-pandas#55]
The `dtype` parameter in one of the examples in the `get_df` function docs is not properly indented.

https://github.com/DrGFreeman/dynamo-pandas/blob/3e51320b3bca4e00b2f1c1c7eb2ad253724c7a46/dynamo_pandas/dynamo_pandas.py#L66-L74

**Comment by sreyan-ghosh** [comment]
Hi @DrGFreeman, I could work on this. Could you assign it to me, please? 
Also, is it ok, if I submit the PR on 1st October since I want it to be a contribution to Hacktoberfest?

My PR would be somewhat like this:

```diff
     >>> df = get_df( 
     ...     table="players", 
     ...     keys=keys(player_id=["player_two", "player_four"]), 
-     ...         dtype={ 
-     ...             "bonus_points": "Int8", 
-     ...             "last_play": "datetime64[ns, UTC]", 
-     ...             # "play_time": "timedelta64[ns]"  # See note below. 
-     ...         } 
-     ...     ) 
+           dtype={ 
+    ...         "bonus_points": "Int8", 
+    ...         "last_play": "datetime64[ns, UTC]", 
+    ...         # "play_time": "timedelta64[ns]"  # See note below. 
+    ...     } 
+    ... ) 
```

**Comment by DrGFreeman** [comment]
Hi @sreyan-ghosh that's fine with me!

**Comment by sreyan-ghosh** [comment]
Could you assign this issue to me please?
