### ISSUE TITLE
error when passing 

### ISSUE THREAD

**Issue by dev-dchellappa** [DrGFreeman/dynamo-pandas#60]
I defined boto3_agrs as a dictionary
```
boto3_args={}
boto3_args["endpoint_url"] = "http://localhost:8000"
boto3_args["aws_access_key_id"] = "fakeMyKeyId"
boto3_args["aws_secret_access_key"] = "fakeSecretAccessKey"
```

And tried to execute 
`df = get_df(table = "Employee", boto3_kwargs = boto3_args)   `

_Errror: TypeError: get_df() got an unexpected keyword argument 'boto3_kwargs'_

But when I checked th soruce code, the method signaure in dynamo_pandas.py is:
`def get_df(*, table, keys=None, attributes=None, dtype=None, boto3_kwargs={}):`

This does have keyword argument boto3_kwargs as a Key word argument.

**Comment by DrGFreeman** [comment]
Hi @dev-dchellappa, The addition of the `boto_kwargs` argument is merged in the master branch but not yet released in the version available on PyPi (currently 1.2.1).  The docs (https://dynamo-pandas.readthedocs.io/) show the API of the latest package available on PyPi.

Can you confirm which version of the package you are using?

**Comment by dev-dchellappa** [comment]
Thank you @DrGFreeman for the quick reply. I am using 1.2.1. So for now, I will configure DynamoDB credentials in AWS CLI.

**Comment by dev-dchellappa** [comment]
@DrGFreeman I am using local DynamoDB. In the CLI, I speficied the below using the `aws configure` command:
```
access_key = fakeMyKeyId
secret_key = fakeSecretAccessKey
region = us-east-1
```
How do i supply to url_endpoint that boto3 must use to connect to local DynamoDB?

**Comment by DrGFreeman** [comment]
This is exactly the purpose of adding the `boto_kwargs` argument to the different functions. If you need to specify a non-default endpoint, either install dynamo-pandas from sources to get the latest development version, or use plain boto3 API calls to interact with DynamoDB.
