### ISSUE TITLE
Boto3_kwargs parameter commit not part of latest release

### ISSUE THREAD

**Issue by wazbekker** [DrGFreeman/dynamo-pandas#64]
Hi

Thanks for putting in the time to create this cool package.  It has been really useful.

I was wondering if you could please create a new release.  I am specifically after this commit with the boto3_kwargs parameter being added:
[Add boto3_kwargs parameter](https://github.com/DrGFreeman/dynamo-pandas/commit/7fb8dc5ac59ac0cd6428ec7deb1f276898a36718)

Thanks again.

**Comment by DrGFreeman** [comment]
Absolutely, thanks for raising the point. That somehow fell off my to-do list. I'll try to get that done in the next few days.

I'm glad the package is useful to you 😃

**Comment by DrGFreeman** [comment]
Version 1.3.0 is now released.

**Comment by wazbekker** [comment]
Thank you very much!
